package protocol

import collectionlist "github.com/arcgolabs/collectionx/list"

func bodyCodecEntries() *collectionlist.List[bodyCodecEntry] {
	return collectionlist.NewList(
		bodyCodecEntry{CmdHandshakeRequest, encodeHandshakeRequest, decodeHandshakeRequest},
		bodyCodecEntry{CmdHandshakeResponse, encodeHandshakeResponse, decodeHandshakeResponse},
		bodyCodecEntry{CmdPingRequest, encodePingRequest, decodePingRequest},
		bodyCodecEntry{CmdPingResponse, encodePingResponse, decodePingResponse},
		bodyCodecEntry{CmdCreateTopicRequest, encodeCreateTopicRequest, decodeCreateTopicRequest},
		bodyCodecEntry{CmdCreateTopicResponse, encodeCreateTopicResponse, decodeCreateTopicResponse},
		bodyCodecEntry{CmdListTopicsResponse, encodeListTopicsResponse, decodeListTopicsResponse},
		bodyCodecEntry{CmdProduceRequest, encodeProduceRequest, decodeProduceRequest},
		bodyCodecEntry{CmdProduceResponse, encodeProduceResponse, decodeProduceResponse},
		bodyCodecEntry{CmdProduceBatchRequest, encodeProduceBatchRequest, decodeProduceBatchRequest},
		bodyCodecEntry{CmdProduceBatchResponse, encodeProduceBatchResponse, decodeProduceBatchResponse},
		bodyCodecEntry{CmdFetchRequest, encodeFetchRequest, decodeFetchRequest},
		bodyCodecEntry{CmdFetchResponse, encodeFetchResponse, decodeFetchResponse},
		bodyCodecEntry{CmdFetchBatchRequest, encodeFetchBatchRequest, decodeFetchBatchRequest},
		bodyCodecEntry{CmdFetchBatchResponse, encodeFetchBatchResponse, decodeFetchBatchResponse},
		bodyCodecEntry{CmdCommitOffsetRequest, encodeCommitOffsetRequest, decodeCommitOffsetRequest},
		bodyCodecEntry{CmdCommitOffsetResponse, encodeCommitOffsetResponse, decodeCommitOffsetResponse},
		bodyCodecEntry{CmdSendDirectRequest, encodeSendDirectRequest, decodeSendDirectRequest},
		bodyCodecEntry{CmdSendDirectResponse, encodeSendDirectResponse, decodeSendDirectResponse},
		bodyCodecEntry{CmdFetchInboxRequest, encodeFetchInboxRequest, decodeFetchInboxRequest},
		bodyCodecEntry{CmdFetchInboxResponse, encodeFetchInboxResponse, decodeFetchInboxResponse},
		bodyCodecEntry{CmdAckDirectRequest, encodeAckDirectRequest, decodeAckDirectRequest},
		bodyCodecEntry{CmdAckDirectResponse, encodeAckDirectResponse, decodeAckDirectResponse},
		bodyCodecEntry{CmdJoinConsumerGroupRequest, encodeJoinConsumerGroupRequest, decodeJoinConsumerGroupRequest},
		bodyCodecEntry{CmdJoinConsumerGroupResponse, encodeJoinConsumerGroupResponse, decodeJoinConsumerGroupResponse},
		bodyCodecEntry{CmdHeartbeatConsumerGroupRequest, encodeHeartbeatConsumerGroupRequest, decodeHeartbeatConsumerGroupRequest},
		bodyCodecEntry{CmdHeartbeatConsumerGroupResponse, encodeHeartbeatConsumerGroupResponse, decodeHeartbeatConsumerGroupResponse},
		bodyCodecEntry{CmdRebalanceConsumerGroupRequest, encodeRebalanceConsumerGroupRequest, decodeRebalanceConsumerGroupRequest},
		bodyCodecEntry{CmdRebalanceConsumerGroupResponse, encodeRebalanceConsumerGroupResponse, decodeRebalanceConsumerGroupResponse},
		bodyCodecEntry{CmdGetConsumerGroupAssignmentRequest, encodeGetConsumerGroupAssignmentRequest, decodeGetConsumerGroupAssignmentRequest},
		bodyCodecEntry{CmdGetConsumerGroupAssignmentResponse, encodeGetConsumerGroupAssignmentResponse, decodeGetConsumerGroupAssignmentResponse},
		bodyCodecEntry{CmdFetchConsumerGroupRequest, encodeFetchConsumerGroupRequest, decodeFetchConsumerGroupRequest},
		bodyCodecEntry{CmdFetchConsumerGroupResponse, encodeFetchConsumerGroupResponse, decodeFetchConsumerGroupResponse},
		bodyCodecEntry{CmdCommitConsumerGroupOffsetRequest, encodeCommitConsumerGroupOffsetRequest, decodeCommitConsumerGroupOffsetRequest},
		bodyCodecEntry{CmdCommitConsumerGroupOffsetResponse, encodeCommitConsumerGroupOffsetResponse, decodeCommitConsumerGroupOffsetResponse},
		bodyCodecEntry{CmdFetchConsumerGroupBatchRequest, encodeFetchConsumerGroupBatchRequest, decodeFetchConsumerGroupBatchRequest},
		bodyCodecEntry{CmdFetchConsumerGroupBatchResponse, encodeFetchConsumerGroupBatchResponse, decodeFetchConsumerGroupBatchResponse},
		bodyCodecEntry{CmdNackRequest, encodeNackRequest, decodeNackRequest},
		bodyCodecEntry{CmdNackResponse, encodeNackResponse, decodeNackResponse},
		bodyCodecEntry{CmdProcessRetryRequest, encodeProcessRetryRequest, decodeProcessRetryRequest},
		bodyCodecEntry{CmdProcessRetryResponse, encodeProcessRetryResponse, decodeProcessRetryResponse},
		bodyCodecEntry{CmdScheduleDelayRequest, encodeScheduleDelayRequest, decodeScheduleDelayRequest},
		bodyCodecEntry{CmdScheduleDelayResponse, encodeScheduleDelayResponse, decodeScheduleDelayResponse},
		bodyCodecEntry{CmdStartRequestRequest, encodeStartRequestRequest, decodeStartRequestRequest},
		bodyCodecEntry{CmdStartRequestResponse, encodeStartRequestResponse, decodeStartRequestResponse},
		bodyCodecEntry{CmdFetchRequestsRequest, encodeFetchRequestsRequest, decodeFetchRequestsRequest},
		bodyCodecEntry{CmdFetchRequestsResponse, encodeFetchRequestsResponse, decodeFetchRequestsResponse},
		bodyCodecEntry{CmdReplyRequest, encodeReplyRequest, decodeReplyRequest},
		bodyCodecEntry{CmdReplyResponse, encodeReplyResponse, decodeReplyResponse},
		bodyCodecEntry{CmdReplyErrorRequest, encodeReplyErrorRequest, decodeReplyErrorRequest},
		bodyCodecEntry{CmdReplyErrorResponse, encodeReplyErrorResponse, decodeReplyErrorResponse},
		bodyCodecEntry{CmdAwaitReplyRequest, encodeAwaitReplyRequest, decodeAwaitReplyRequest},
		bodyCodecEntry{CmdAwaitReplyResponse, encodeAwaitReplyResponse, decodeAwaitReplyResponse},
		bodyCodecEntry{CmdErrorResponse, encodeErrorResponse, decodeErrorResponse},
	)
}
